### ISSUE TITLE
[Bug]段落标记丢失

### ISSUE THREAD

**Issue by wuzimi** [ac1982/eBook-translator#1]
您好，今天尝试使用您的代码进行小段翻译。发现译文进行了合并。下面是原英文，翻译后前面六七个段落都合并成一个段落，后面几个正常，请问如何解决？谢谢!
And that’s where a lot of the unconscious bias work comes in. And what’s your own cognitive style and how does it impact how you think in what you do? That whole area we find is very important for people. The big enemy is ego. You really need to be a great leader on one hand, have a super powerful sense of self, and I can have an impact, but to also be able to be humble and be an open system so you’re able to be wrong.

CURT NICKISCH: This also makes you less predictable because you are more dynamic and especially with CEOs or really any leaders, sometimes people only have so many interactions with that person. And it’s helpful for team members to know, “This is the way this person likes to receive information when they’ve said this before, that means this.” And here’s a situation where CEOs may be acting differently in different situations and that might make them harder to read.

CAROL KAUFFMAN: It may take getting used to, I think what we’re talking about though is ideally somebody operating from their core, and it also doesn’t have to be so radical. It may be that I gently lean in with you at the beginning of a meeting when I want to get things going and when they do, I lean back and let people bring in the data, then be aware of the people issues and then be comfortable with silence.

You’ve just done lean in back with and don’t lean, but it can be subtle. The core is your capacity to make space, and I think that’s what brings it together. It’s not going to be wild and jerky, but this leader is able to be agile and to respond to what’s coming their way rather than always a cookie cutter leader.

CURT NICKISCH: You can do this without being hard to read or coming across as wishy-washy.

CAROL KAUFFMAN: Yeah. Or as you said, jolting people all the time because the toughest leader is the one that’s deeply unpredictable, but it’s emotionally unpredictable whether they’re nice and supportive one time and then really caustic another. Better to be caustic all the time, then caustic and then nice. I think you’re picking up on that in a way I hadn’t really thought of, but how do you be centered and agile? Rather than this unpredictable, which reduces psychological safety.

CURT NICKISCH: You want to be consistent and agile.

CAROL KAUFFMAN: Yeah, exactly.

CURT NICKISCH: Is this completely an individual leadership thing or can this be part of a lead leadership culture or system at an organization?

CAROL KAUFFMAN: I love that question. Your question is how do you make it part of the culture and the core leadership capabilities that you want to flow through an organization, which basically is this scalable.

CURT NICKISCH: A culture of decision making, yeah.

CAROL KAUFFMAN: One of the things we do is we also have a couple of meta tools, and one of them is something I called coach by numbers or the 10 of 10 conversation. That one ripples out very quickly. Ten of 10, that’s basically, you’ve heard this in positive psychology, et cetera, but it makes it really very specific, which is if you wanted to accomplish something outside or inside, if you were a 10 out of 10, what would you look like? If you were going to work on something, it can be hypothetical, what would it be?

What we would start out with, I would say if you were a 10 out of 10 on this, what would you look like? What would you be doing? And we would really spell out not what the problem is, but if you were really good at it.

CURT NICKISCH: What would it look like? Yeah.

CAROL KAUFFMAN: What would it look like? Paint the picture, what would people be seeing if I had a video camera, if I was listening to you, what are you thinking, feeling, doing? And really paint that picture 10 out of 10 and that’s not easy. Then the second question would be, on that scale of one to 10, what number would you give yourself now? What would you rate yourself?

We’ll pretend that you said a six. The next question, which I think of as the question that counts is what are you doing that you are a six and not a 5.5 and really make you think. Cognitively, it’s much easier for you to describe what you’re doing wrong. It is much easier for you to be critical.

And we would really, really unpack that with the same intensity of something that went horribly wrong and say, “Well, what else did you do wrong? What else did you wrong?” That same energy, but a positive confrontation and truly make you map it out and it’s hard. Only then would we go to, “Okay, what could you do over the next eight weeks to get from a six to a 6.5?” This is a conversation you can have with yourself.

It works really well with the team. Any interaction, it works well at home and it’s like a fractal conversation. It’s a pattern of a conversation that can just ripple out through a company. Even just the 10 out of 10 part. To say, we once did a strategy consultation, David Noble and I, and they came up with their 10 strategies and this guy walked up and said, “Okay, if this strategy, we know strategy meetings, what do you do?” We tear things apart. That’s what funny is. Instead, he said, “If this strategy was a 10 out of 10, what would it look like?” And in that moment, that orientation basically frackled out through the entire company. Now in every business development conversation, what would a 10 look like for you? That question alone is very powerful, and what did I do right conversation is very powerful.

CURT NICKISCH: When people do this, what are some of the surprising and great things that can happen?

**Comment by ac1982** [comment]
因为您提交的内容为文本，行末标记（end of line）采用的是```\n```或者```\r```，我画蛇添足地将类似的符号删除了。Epub的段落则使用HTML标签进行分段，例如"<br />"，这样不算“空字符”，就不会出现这个问题。您提到的段落合并正是由于这个原因。解决这个问题相当容易。请问您能将epub源文件提供到这里吗？这样我便可以进行测试。

**Comment by ac1982** [comment]
I have updated the code to preserve end-of-line characters such as ```\n```, ```\r```, and so on.

**Comment by ac1982** [comment]
#ff52b6db443d4d82edc67b165c8292d99da0a5e3

**Comment by wuzimi** [comment]
您好，我更新了代码，问题依旧。翻译结果如下，前面的段落还是进行了合并，后面几个段落就是没合并的。我用的纯文本转的epub再进行翻译。
这就是许多无意识偏见工作的重点所在。你自己的认知风格是什么，它如何影响你的思考和行为？我们发现，这整个领域对人们非常重要。大敌是自我。你需要成为一位伟大的领袖，一方面拥有超强的自我意识，能够产生影响，但也要能够谦虚，成为一个开放的系统，这样你才能犯错。
CURT
NICKISCH：这也使你更不可预测，因为你更具动态性，特别是对于CEO或任何领导者来说，有时人们只与这个人有很少的互动。对于团队成员来说，知道“这个人喜欢在这种情况下接收信息，当他们说这个时，意味着这个”，这是有帮助的。这里有一种情况，CEO在不同的情况下可能会表现出不同的行为，这可能会使他们更难以读懂。
CAROL
KAUFFMAN：我认为这可能需要适应，我们所说的理想情况是某人从他们的核心操作，而且它也不必如此激进。也许我在会议开始时会轻轻地倾斜，当我想让事情开始时，我会向后倾斜，让人们带来数据，然后关注人员问题，并且对沉默感到舒适。
你刚刚做了倾斜和向后倾斜，但它可以很微妙。核心是你创造空间的能力，我认为这就是将其结合在一起的关键。它不会很疯狂，但这位领导者能够灵活应对，对他们的方式做出回应，而不总是一个模板式的领导者。
CURT NICKISCH：你可以做到这一点，而不会让人难以读懂或显得犹豫不决。 CAROL
KAUFFMAN：是的。或者像你说的，总是让人感到震惊，因为最难以预测的领导者是情绪上的不可预测性，他们有时很友好和支持，有时却非常尖刻。最好总是尖刻，然后再友好。我认为你以一种我从未想过的方式理解了这一点，但如何保持中心和灵活呢？而不是这种不可预测性，这会降低心理安全感。
CURT NICKISCH：你想保持一致和灵活。 CAROL
KAUFFMAN：是的，完全是个人领导力的事情，还是可以成为组织中领导文化或系统的一部分？
我喜欢这个问题。你的问题是如何使其成为文化和核心领导能力，这基本上是可扩展的。 CURT NICKISCH：决策文化，是的。 CAROL
KAUFFMAN：我们做的事情之一是我们还有一些元工具，其中之一是我称之为“数字教练”或“10对10的对话”。这个工具非常快速地扩散。
10对10，基本上，你在外部或内部想要实现某些事情，如果你是10分中的10分，你会是什么样子？如果你要解决某些问题，它可以是假设的，那么它会是什么？

我们会先问你，如果你在这方面是10分中的10分，你会是什么样子？你会做什么？我们会真正描述的不是问题所在，而是如果你真的很擅长这个领域，你会是什么样子。

CURT NICKISCH: 会是什么样子？好的。

CAROL KAUFFMAN:
会是什么样子？描绘一下，如果我有一个摄像机，如果我在听你说话，你在想什么，感觉什么，做什么？真正描绘出10分中的10分，这并不容易。

Alex ***@***.***> 于2023年5月9日周二 18:22写道：

**Comment by ac1982** [comment]
已经解决，我减小了Buffer的大小，因为GPT-3.5-turbo会丢失system信息。你可以pull最新的版本，再次尝试。感谢你的反馈。
[test.zip](https://github.com/ac1982/eBook-translator/files/11439137/test.zip)

附件是测试的结果，直接用你的纯文本转成epub后翻译的。

**Comment by wuzimi** [comment]
测试了没问题，希望今后能增加对更多格式的支持，比如text，docx等等。另外，这个代码是不是没有采用并发？如果并发处理是否更快？我用的付费api，所以有这个需求。谢谢！

Alex ***@***.***> 于2023年5月10日周三 15:20写道：

**Comment by ac1982** [comment]
你把需求另外开个issue吧，我commit的时候好关联到新的issue。比如并发，我正在做。至于text或者docx，随后跟进吧。

**Comment by wuzimi** [comment]
Ok.

Alex ***@***.***> 于 2023年5月10日周三 18:46写道：

**Comment by wuzimi** [comment]
已经提了2个功能要求，开了新的issue,谢谢！

Xiaomi Wu ***@***.***> 于2023年5月10日周三 20:00写道：

**Comment by wuzimi** [comment]
您好！最近在使用翻译插件，反复遇到之前遇到过的合并段落问题，也就是原文中一个个的自然段落，翻译后被合并在一起。今天专门看了日志，发现出现翻译后合并的段落，在日志里对应的翻译结果中缺少这张{{id_142}}信息。比如下面的原文：
原文：<p/>Charlie Munger (21m 52s): And people like China have these enormous
reserves at dollars be the money we make by think of the money people give
us, where we always just print up these pieces of paper. {{id_135}} <p/>Ben
Gilbert (22m 4s): Yep. And what about the common person in some of these
less fortunate countries who don’t have access to US dollars? {{id_136}}
<p/>Charlie Munger (22m 12s): Well they do. If they ever get any money. The
dollar’s very fungal. You can always buy one anywhere. {{id_137}} <p/>Ben
Gilbert (22m 21s): I’m curious, back to this point of the role of venture
capital in a society. If you could design a perfect system to fund a
nation. Well I think {{id_138}} <p/>Charlie Munger (22m 28s): It’s a very
legitimate business if you do it right. If you wanna give the right people
the power and nurture them, help them. And you know a lot about the tricks
of the game so you can help them run their business yet not interfere with
‘em so much. They hate you by and large. Having bumped into a lot of people
in the businesses with venture capital financing, I would say the ordinary
rule is that people in the business doing the work, they more often than
not, they hate the venture capitalists. They don’t feel they’re their
partner trying to help them to become they, they’re only taking care of
themselves and so on and so on. {{id_139}} <p/>Charlie Munger (23m 9s): And
they don’t like them. {{id_140}} <p/>Ben Gilbert (23m 10s): How could it
work differently? Yeah. {{id_141}} <p/>Charlie Munger (23m 12s): Well I I,
but that’s not true in Berkshire. You see RBOE, they know we’re not trying
to discard them to the highest bid. See if some oil investment banker
offers us 20 times earnings or some lousy business, we don’t sell. Hmm. If
it’s a problem business we’ve never been able to fix, we’ll sell it. But
it’s a halfway decent business. We never sell anything. And that gives us
this reputation of staying with things which helps us. {{id_142}}
-----------------------------------
译文：<p/>查理·芒格（21分52秒）：而像中国这样的国家拥有巨额的美元储备，这些钱是我们通过印刷纸币获得的，想想人们给我们的钱，我们总是可以随意印刷这些纸币。<p/>本·吉尔伯特（22分4秒）：是的。那么对于一些不幸的国家中的普通人来说，他们无法获得美元怎么办？<p/>查理·芒格（22分12秒）：他们可以。只要他们有了钱。美元非常流通。你随时可以在任何地方买到美元。<p/>本·吉尔伯特（22分21秒）：我很好奇，回到风险投资在社会中的角色这一点。如果你能设计一个完美的系统来资助一个国家。我认为...<p/>查理·芒格（22分28秒）：如果你做得对，这是一个非常合法的业务。如果你想给合适的人权力并培养他们，帮助他们。你对这个游戏的诀窍了如指掌，所以你可以帮助他们经营业务，但又不会干涉他们太多。他们大多数情况下讨厌你。在与接受风险投资融资的企业的许多人接触过后，我可以说普遍规则是从事工作的人，他们更多时候讨厌风险投资家。他们觉得他们不是他们的合作伙伴，试图帮助他们成为他们自己，他们只关心自己等等。<p/>查理·芒格（23分9秒）：他们不喜欢他们。<p/>本·吉尔伯特（23分10秒）：那么它可以有不同的工作方式吗？是的。<p/>查理·芒格（23分12秒）：嗯，但在伯克希尔公司不是这样的。你看，RBOE，他们知道我们不是为了最高的出价而抛弃他们。看看如果一些石油投资银行家给我们提供20倍的收益或者一些糟糕的生意，我们不会卖掉。嗯，如果是一个我们从未能够解决的问题业务，我们会卖掉。但如果是一个过得去的生意，我们从不卖任何东西。这给了我们一个坚守事物的声誉，这对我们有所帮助。

如果是正常显示的，原文和译文都会保留段落的ID信息，比如下面：
原文：<p/>Charlie Munger (25m 24s): Well, they’re starting to do it. The
endowments have started to say to the, all these people that charge three
and 30 or whatever they charge, they said, we’ll pay your three and 30, but
we’re gonna put in twice as much money and in the next half you’ll get
nothing on it. Or you’re going ride Perry Pass, who on some of your
investments. So the fees go down by 50%. That’ll take a lot of the fun out
of it. Fees down 50%. And that’s happening all over America. They feel had
misled, irritated. They’ve looked foolish to their own trustees. {{id_149}}
<p/>David Rosenthal (26m 6s): One of the issues I think in investing right
now you mentioned about venture capital, but I think it’s true everywhere.
It’s like there’s just so much capital and so much competition. We’re so
far removed from the cigar butt era. We’re in the opposite of the cigar
butt era these days. Are there opportunities {{id_150}} <p/>Charlie Munger
(26m 23s): Out there? Somebody will find a few things but it gets harder
and harder. I would argue one of the easiest ones was when they decided a
little group around Home Depot, they would copy the Costco Metal and home
improvements. And that was basically a good idea. And think of the money
they made doing it. {{id_151}} <p/>David Rosenthal (26m 46s): Yeah. Bernie
Marcus. {{id_152}} <p/>Charlie Munger (26m 48s): Yeah. It was a direct copy
of Costco. {{id_153}} <p/>Ben Gilbert (26m 53s): Do you think there are
more opportunities to copy Costco? Well {{id_154}} <p/>Charlie Munger (26m
56s): There was another one at Costco, Florida Decor. It’s the current
imitator and it’s just, it’s in vinyl wood imitating vinyl flooring.
They’re, they’re running a Costco model. {{id_155}} <p/>Ben Gilbert (27m
11s): Huh. {{id_156}} <p/>Charlie Munger (27m 12s): And they keep adding
miscellaneous stuff to it too. {{id_157}} <p/>Ben Gilbert (27m 15s): It’s
the miscellaneous stuff that’ll eventually kill you though. {{id_158}}
-----------------------------------
译文：<p/>查理·芒格（25分24秒）：他们开始这样做了。捐赠基金已经开始告诉那些收取3%和30%费用的人，他们说，我们会支付你们的3%和30%，但我们会投入两倍的资金，在下半年你们将一无所获。或者你们可以跟随一些你们的投资中的佩里·帕斯。所以费用降低了50%。这将让很多乐趣消失。费用降低了50%。这种情况在美国各地都在发生。他们觉得被误导了，感到恼怒。他们在自己的受托人面前显得很愚蠢。{{id_149}}
<p/>大卫·罗森塔尔（26分6秒）：我认为目前投资的一个问题是，你提到了风险投资，但我认为这个问题在任何地方都存在。现在有那么多资本和竞争。我们已经远离了雪茄蒂时代。如今我们正处于雪茄蒂时代的反面。有机会吗？{{id_150}}
<p/>查理·芒格（26分23秒）：有人会找到一些机会，但越来越难了。我认为最容易的一个是当他们决定围绕家得宝成立一个小团队，他们会模仿好市多的金属和家居装修。这基本上是一个好主意。想想他们赚了多少钱。{{id_151}}
<p/>大卫·罗森塔尔（26分46秒）：是的。伯尼·马库斯。{{id_152}}
<p/>查理·芒格（26分48秒）：是的。这是对好市多的直接模仿。{{id_153}}
<p/>本·吉尔伯特（26分53秒）：你认为还有更多模仿好市多的机会吗？好吧。{{id_154}}
<p/>查理·芒格（26分56秒）：好市多还有另一个模仿者，佛罗里达装饰。他们在模仿乙烯基木地板。他们正在运营一个好市多的模式。{{id_155}}
<p/>本·吉尔伯特（27分11秒）：哦。{{id_156}} <p/>查理·芒格（27分12秒）：而且他们还不断添加其他杂项。{{id_157}}
<p/>本·吉尔伯特（27分15秒）：但最终会害了你的是那些杂项。{{id_158}}

这样看，翻译后id信息是输出结果有大段合并段落的原因。由于我主要使用双语对照，内容越长，出现大段合并的可能性越高，人工去编辑非常耗时。不知道我的发现是否有助于解决目前的问题？另外，自己尝试不使用并发，而是改用单线程，似乎也能减少这种情况的发生。

谢谢！

**Comment by ac1982** [comment]
我晚上解决下这个问题，你可以先使用单线程——确实有帮助的，我自己测试下来也是如此。

**Comment by ac1982** [comment]
1. 如果你处理的事情是“工作”范畴，那么建议你直接在配置把模型调整为```gpt-4```，虽然会贵一点，但是它能更好的理解system参数；
2. 我调整默认的线程为单进程，并且升级了依赖。
3. 我已经通过修复提示词，强调了占位符的保留。你给我的部分内容翻译得到的结果：
```
<p/>查理·芒格（25分24秒）：嗯，他们开始这样做了。捐赠基金已经开始对那些收取3%和30%费用的人说，我们会支付你们的3%和30%，但是我们会投入两倍的资金，并且在下半年你们将一无所获。或者你们会跟随佩里·帕斯（Perry Pass）在你们的一些投资上。所以费用降低了50%。这将会让很多乐趣消失。费用降低了50%。这种情况在美国各地都在发生。他们感到被误导、恼怒。他们在自己的受托人面前显得愚蠢。{{id_149}}
<p/>大卫·罗森塔尔（26分6秒）：我认为当前投资的一个问题是，你提到了风险投资，但我认为这个问题在任何地方都存在。现在有太多的资本和竞争。我们已经远离了雪茄蒂时代。如今我们正处于雪茄蒂时代的反面。是否存在机会？{{id_150}}
<p/>查理·芒格（26分23秒）：有人会找到一些机会，但越来越难。我认为最容易的一个是当他们决定围绕家得宝（Home Depot）的一个小团队，复制了好市多（Costco）的金属和家居装修。那基本上是个好主意。想想他们赚了多少钱。{{id_151}}
<p/>大卫·罗森塔尔（26分46秒）：是的。伯尼·马库斯（Bernie Marcus）。{{id_152}}
<p/>查理·芒格（26分48秒）：是的。那是对好市多的直接复制。{{id_153}}
<p/>本·吉尔伯特（26分53秒）：你认为还有更多复制好市多的机会吗？嗯。{{id_154}}
<p/>查理·芒格（26分56秒）：在好市多还有另一个，佛罗里达装饰品。它是目前的模仿者，它只是在模仿木纹地板。他们在运营一个好市多模式。{{id_155}}
<p/>本·吉尔伯特（27分11秒）：嗯。{{id_156}}
<p/>查理·芒格（27分12秒）：而且他们还不断添加其他杂项商品。{{id_157}}
<p/>本·吉尔伯特（27分15秒）：但最终会害死你的是那些杂项商品。{{id_158}}
```

若是还有问题，请反馈。

**Comment by wuzimi** [comment]
感谢，我再试下！

Alex ***@***.***> 于 2023年11月6日周一 16:14写道：
