### ISSUE TITLE
希望再增加2个功能

### ISSUE THREAD

**Issue by wuzimi** [ac1982/eBook-translator#2]
使用openai进行翻译时，一个是支持并发处理，二是支持导出双语对照。谢谢！

**Comment by ac1982** [comment]
现在已经支持多进程，你Pull最新版本即可。虽然我也是订阅的API，但是OpenAI的API在高并发的时候并不是特别稳定。再说翻译书籍好像不是那么紧迫吧，我的意思是，最好还是单进程处理。如果预算充沛，在配置里面是支撑gpt-4模型，效果会更好。原因是，gpt-4不会丢失system的提示，而gpt-3.5-turbo这件事情会偶有错误。

**Comment by wuzimi** [comment]
感谢…明天试试哈。

Alex ***@***.***> 于 2023年5月18日周四 22:16写道：

**Comment by wuzimi** [comment]
您好，关于config参数，请教几个问题：

 "openai_api_key": "sk-your-key-here",
  "model": "gpt-3.5-turbo",
  "system": "Act as e-book translator to Simplified Chinese. Preserve the
original language for elements such as programming code, computer commands,
variable/function/class names, proper nouns, file names and paths, URLs,
email addresses, mathematical formulas and symbols, abbreviations,
copyright information, and country-specific measurements, currency, code
for end-of-line, and date formats.",
  "max_workers": null,
  "test": false,
  "items_number":10

1.System prompt: 如果我不是用来翻译书，系统提示词这里我是不是可以简化而不影响原文的段落格式？
2. max_workers": null, 这个参数时设置并发？应该如何设置，是不是要设置并发数量？
3.   "test": false,
  "items_number":10
这里的item number是什么，如何设置？

谢谢！

Alex ***@***.***> 于2023年5月18日周四 22:16写道：

**Comment by ac1982** [comment]
1. system prompt是优先级最高的提示词，所以如果你不是用来翻译电子书，只是要翻译文本，那么可以短一些，但是你最好在test环境看看效果.
2. max_workers 不设置的时候是并发，原因是源代码在没有该参数值为null的时候，并发数等于计算机核心数
3. epub电子书实际上是很多个xhtml格式的文件，每个文件都是一个item。一般来说一个目录，一个序言，一个章节就是一个item。所以item的数量是在test环境下，你需要遍历的item数量，只在test环境有效。这个设置取决于你想在测试环境遍历多少item。我自己测试会根据电子书看情况，假如目录，序，第一章为目标，那么只需要设置为3.

**Comment by wuzimi** [comment]
今天尝试翻译了有50个段落的文章，翻译后发现段落少了很多，原来译文对不少段落进行了合并，这个问题好解决吗？

Alex ***@***.***> 于2023年5月18日周四 22:16写道：

**Comment by ac1982** [comment]
你给我具体的东西吧，我测试下。我最近用它翻译了不少书，主要是自己看，并没有出现类似问题。所以，我需要样本来复现，定位问题，才能知道是否需要解决，如何解决。

**Comment by wuzimi** [comment]
你直接复制这段文本吧。我把它转为epub后用你的应用翻译的。

We all know that creativity is the backbone of innovation and, ultimately,
business success. But we don’t always think deeply about how creative
people get their ideas and the steps we might take to do the same.
Gabriella Rosen Kellerman, a physician and chief product and chief
innovation officer at BetterUp, and Martin Seligman, a professor of
psychology at the University of Pennsylvania, say there are four types of
creativity — integration, splitting, figure-ground reversal, and distal
thinking — and explain how each shows up at work. Amid startling advances
in artificial intelligence, people who hone these skills will set
themselves apart. Kellerman and Seligman are the authors of the HBR article
“Cultivating the Four Kinds of Creativity” and the book Tomorrowmind.

ALISON BEARD: Welcome to the HBR IdeaCast from Harvard Business Review. I’m
Alison Beard.

Fears about robots taking over our jobs ebb and flow over time, but with
the recent rise of AI tools like DALL·E, which can scrape the internet to
create some not bad art and design work, and Chat GPT, which can mimic
human writing and even pass medical, bar and business school exams, now
everyone seems to be worried. But today’s guests argue that there are a few
things artificial intelligence can’t yet replicate, chief among them, human
creativity. And they have some advice for how to better cultivate it, in
yourself, your team, and your organization.

Gabriella Rosen Kellerman is a physician and chief product officer and
chief innovation officer at BetterUp,and Martin Seligman is a professor of
psychology at the University of Pennsylvania. They’re co-authors of the new
book, Tomorrowmind, and the HBR article, “Cultivating the Four Kinds of
Creativity”. Welcome to both of you.

MARTIN SELIGMAN: Hi, Alison.

GABRIELLA ROSEN KELLERMAN: Great to be here, Alison.

ALISON BEARD: Gabriella, let’s start with you. Just for context, why is
creativity such an important way for us to set ourselves apart, not just
from robots but also from our peers and competitors?

GABRIELLA ROSEN KELLERMAN: So the robot part’s a little bit important to
start with. We are seeing the less creative, more rote parts of our job
taken over by automation. And that, in our view, is probably a good thing.
It means our jobs become more interesting and more human. And part of the
overarching climate that this is happening within is changing so rapidly
and at such a global scale that the challenges we’re facing are very
different than in previous eras. They’re novel, it’s not the same thing
recurring in different forms.

They’re unpredictable, they’re uncertain. And so it requires inherently a
creative and novel approach because it’s a new problem. Those of us who can
rise to the opportunity to see those challenges as times to shine as
creatives, as times to put forward our ideas and lean into that native
creativity, will thrive in this environment. And part of our work and our
hope is to empower people to identify as creatives and to build that muscle.

ALISON BEARD: And Marty, you and Gabriella are both psychologists. What
role does creativity play in mental health? Why are these issues that you
two think about?

MARTIN SELIGMAN: Well, mental health increasingly depends on creative
solutions to personal problems as well as problems at work. And in order
for us to be creative in our lives, we need to know something more about
what creativity actually is. And the literature on creativity is not very
helpful. It basically has told us that creativity is divergent thinking.

I think that’s true, but what Gabriella and I have been after is what kinds
of divergent thinking are there? Can you identify the kinds, and then for
the problems you have, in your own life, at your corporation, or in what I
do, which is science, what kind of creativity, what kind of divergent
thinking is going to work best with the problems you’re looking at?

ALISON BEARD: Yeah, and I think that’s useful because we so often think of
creative jobs as the people who are in the art department or the editorial
department. You think about brainstorming meetings, innovation. But the
idea is that you can be creative and you should be creative in any kind of
job, right?

GABRIELLA ROSEN KELLERMAN: Yeah, that’s correct. And particularly at the
edges of the business, which is often customer service or the front lines
of receiving and exchanging paperwork, there’s really important signals
happening and really important opportunities to formulate creative
solutions to these challenges, which then become opportunities. So the
businesses that will succeed are the ones where those folks at the edges
are empowered, are creative, and where there’s a fast and easy way of
transmitting their innovations to the rest of the business.

ALISON BEARD: So Marty, if we’re going to break down just divergent
thinking into more specific kinds of creativity, just quickly walk me
through the four types that you’ve outlined.

MARTIN SELIGMAN: If we look at the history of science, there are four huge
moves that people make for creative solutions in science. The first is
integration, and that’s seeing that things that look very different are
really the same. The second is the reverse of that. That’s splitting, and
seeing that something that is claimed to be the same is really very
different. The third kind, the kind I use most in my life, is figure-ground
reversal. And that says that the solution to the problem is not going to be
found in the foreground, it’s going to be found in background premises that
are wrong. And the fourth kind is distal thinking, and that’s the ability
to think about things that are very different from the here and now:
different in time, different in space and different in culture.

ALISON BEARD: And I’d love to drill down into how all these different types
actually show up in the workplace. So give me an example of integration.

GABRIELLA ROSEN KELLERMAN: So a very famous example of integration from the
last couple decades is the iPhone. So originally, maybe 40 years ago, you
had some sort of music player on a console, you had a phone hanging on the
wall, you had a camera with film that would be dropped off at the drugstore
to be developed. Over time, those were all digitized.

And then the integration victory was realizing that once those things were
digitized, the acts of storing and processing and then accessing the data
through each of those was analogous and could be therefore combined into a
single device. And now many of us sitting next to us right now have a phone
that’s also a camera and a music player. Lots of integrative thinking
victories had to happen to get there, and engineering that followed suit in
terms of integrating common systems for these very different use cases.

Marketing is a great example. There’s often marketing challenges where
we’re trying to solve for a particular use case or persona of a customer,
and we realize that there’s an analogy to what we would’ve thought of as a
very different persona, but actually the needs are common. And so the
solutions that worked in one arena can then be brought over and applicable
and sometimes even more successful for that second persona. We see it in
sales, in marketing, really across the board, across the functions.

ALISON BEARD: Okay. Marty, what about splitting? What’s a real world
example of that?

MARTIN SELIGMAN: Well, splitting is seeing that things that look like
they’re the same are really different. In science, the great precedent for
splitting is the table of the elements. Earth, air, fire, and water, those
were the Greek elements. And we now have, at last count, 119 splits for
that. In medicine it’s been very important to take syndromes that look like
they’re the same, in smallpox, for example, small poxes on the face and
fever, to divide that into the kind of smallpox that kills you, variola
major, and the kind of smallpox that just produces the symptoms but is not
deadly. And that’s been crucial to understanding smallpox.

GABRIELLA ROSEN KELLERMAN: I would guess that splitting is one of the
creative acts that we are most used to doing at work. Whenever we see
product differentiation, so a broad product line that started as one thing
and then starts to differentiate into different streams of business, that’s
theoretically an act of splitting. It depends, for our definition, depends
how that came to be. But if you’re fine-tuning it to different audiences
and you’re realizing there’s inherently different value propositions for a
single product, that is an act of splitting. And that can happen, by the
way, in an R&D team or it can happen in a product marketing team. It can
happen with a frontline salesperson who realizes that there’s a different
way to position that product. It can also happen on the contracting side.
So there’s really a lot of different parts of the value chain within the
business where that splitting insight can arise and even be enacted.

ALISON BEARD: Okay. Figure-ground reversal is up next. That strikes me as
something that’s quite strategic. Marty, could you give us an example?

MARTIN SELIGMAN: I think the most important discovery in neuroscience of my
lifetime was a remarkable figure-ground reversal. Like many people who are
interested in what brain circuits light up when you’re doing a specific
task, like listening to this podcast for example, how do you find out?
Well, there are a thousand studies of the following form to ask what part
of the brain lights up when you’re doing an external task. We put people
into the donut and we give them a lecture to listen to, anagrams to solve,
external problems. But we also run a control group, because you have to
contrast it to something. So we ask people, “Oh, just lie there and don’t
do anything.”

Well, what showed up was a huge reversal. And that is, if you look at what
lights up when you’re listening to this podcast, it’s very noisy. You have
to be a really good statistician to pull out what’s going on. But if you
look at what lights up when I ask you just to lie there and don’t do
anything, it is so regular that we call it the default circuit. And it
turns out to be the very same circuit that lights up if I ask you to plan
for the future. So it turns out that the creativity circuit, the
imagination circuit, was discovered by looking not at what we do when we’re
focused on a task, but what we do when we lie there and are asked not to do
anything. 50% of the time, you’re planning for the future.

ALISON BEARD: That’s very meta. You learned something about creativity by
using figure-ground reversal, which is a type of creativity.

GABRIELLA ROSEN KELLERMAN: We also see figure-ground reversal in industry.
These are stories you’ll hear of some sort of tool that was built for
internal purposes and then it became the successful product. Slack is a
great example of this. Stewart Butterfield started the company Tiny Speck,
a video game company, and the engineers developed this messaging system for
their own purposes to communicate across the company. It became so
successful as a messaging app that of course today we know Slack as a
messaging company, and a very successful one at that, rather than as a
video game company.

MARTIN SELIGMAN: And let me just add one thing to that, if I may. One of my
favorite examples is GPS. And the way GPS came about was in 1958, I think,
the Russians launched Sputnik into space and American military wanted to
track where it was. And so to do that, they had to look at two different
places on earth and zoom in on Sputnik. By doing it to two different
places, you could get both the speed and where it was. And then people
said, well, how about if we reversed this and we wanted to know where
Alison was on earth right now? Well, we’d need two different satellites out
in space looking at Alison. And so GPS was a profound figure-ground
reversal.

ALISON BEARD: And now we can’t imagine living without it. That’s pretty
extraordinary. So finally Gabriella, let’s talk about distal thinking. Is
this the kind of creativity that we think about when we’re talking about
innovation and entrepreneurship and invention?

GABRIELLA ROSEN KELLERMAN: It’s the kind of thinking we imagine with the
lone creative genius who’s able to think of these futures so different from
what we have today that it takes a moment just to wrap our head around the
words they’re using and the vision they’re painting. That is a type of
divergent thinking that is unique to some of us.

ALISON BEARD: And so how do people bridge that gap between the present and
the future in a way that others can’t? How do they make other people see
what they see?

GABRIELLA ROSEN KELLERMAN: There’s lots of examples over the last hundred
years of innovators who were ahead of the market. And subsequently their
distal ideas became very successful, but they saw very little of the
monetary success because they were too far ahead of it. So we proposed two
different strategies to bridge the gap between the distal invention and
market which is not yet ready for it. The first one is by accelerating
market maturity, doing this through promotions, partnership and focus
launches.

So an example of this would be PayPal. When PayPal first came to be, people
may recall that the primary use case, or one of the primary use cases was
eBay. People weren’t using digital payments broadly, but it was very common
to do so on the site eBay. PayPal and eBay formed a strategic partnership
and eBay even acquired PayPal. Eventually, PayPal became a broader-based
offering with lots more applications as the market caught up. But that was
a really successful incubation for PayPal during that 10-15 year period.

The second strategy is what we call backwards innovation. So this is where
you have intermediary kind of stepping stone products between where we are
today and where you’re trying to get people. Self-driving cars offer a good
look at this, where there is technology that would let people take their
hands off the wheel more than they’re willing to do today. But the cars
that we use, for lots of reasons, don’t have that in place. And one of
those reasons is simply consumer readiness.

And so there are these intermediary products that are helping us along the
way. Tesla’s a great example of this and they have language for different
modalities of hands-off driving that help people get more comfortable with
this ultimate vision they have, which still feels funny to us today, of not
actually having our hands on the wheel and getting from one place to
another.

MARTIN SELIGMAN: I think of distal thinking as particular genius. I’m a
verbal thinker, but when I try to understand DNA and Francis Crick’s
discovery of the double helix, this notion of a self-replicating double
helix is so difficult for me to wrap my mind around. Einstein was a visual
thinker. His ability to conceive of time in a visual way is what gave us
both special relativity and general relativity. So for me, distal thinking
differs from person to person and there are some people who are geniuses at
it.

ALISON BEARD: We’ve talked about these hugely successful products and
companies and inventions, but part of your premise is that all of us, the
non-geniuses, can cultivate all of these types of creativity if it doesn’t
come to us naturally?

GABRIELLA ROSEN KELLERMAN: We believe that we can cultivate creativity.
There are methods for how to build these different muscles. There’s going
to be types within the four that feel more native to some of us than
others. And gaining self-awareness of our creative strengths is part of the
exercise that we’re proposing, so that we can work on those areas where
we’re less strong, but also surround ourselves with thinkers who are
complementary so that at the team level, at the organizational level, we’re
responding to creative opportunities as robustly as possible.

ALISON BEARD: You talk in the book about creativity hygiene, things that we
should all do all the time to boost our muscles, as you say. So what are
some of those daily habits that you’d like us to adopt?

GABRIELLA ROSEN KELLERMAN: The idea of creativity hygiene is analogous to
sleep hygiene, with the notion that sleep, like creativity, is something we
want to be able to do readily, but involves non-conscious processes. And
therefore surrounding ourselves with behavioral techniques and contextual
cues that will optimize for that is the right approach rather than, for
example, telling ourselves, just be creative or just go to sleep. Our
brains just don’t quite work like that.

For creativity, we’re proposing a few different threads of “hygiene,” by
which we really just mean behavioral shifts. One of them is all about
seeking novelty. So how do we feed that default mode network that Marty was
talking about with the most rich, divergent materials so that when we are
in those acts of association that happen in these very creative parts of
our minds, they’re drawing from the richest soil possible?

So things like branching out socially, breaking up our routine, taking a
different route to and from work, browsing broadly, whether that’s
literally in a bookstore or online. Another important thread of creativity
hygiene is dialing in incubation period. Incubation is the period in
between really focused work on a particular problem. We’re working on it,
but in the background of our conscious minds, and we know that there are
activities that interfere with high-quality incubation.

So busy work, messaging, meetings, lots of things that we spend our days at
work doing, they interfere with high quality incubation. What’s best for
incubation of creative problems is doing just enough. So tasks that require
a minimal amount of conscious attention, but still some. You don’t want to
just be lying in bed. But taking a walk, gardening, showering, all of these
things that you’re sort of on autopilot. This is what leads to the richest
daydreaming, the richest incubation and then will result in richer output.

MARTIN SELIGMAN: I’m a great advocate of daydreaming and dreaming. One very
interesting property of the default circuit is there seems to be a temporal
pattern all day long in which you listen to what I’m saying for about 90
seconds, and then you go inward, the default circuit turns on, and you do
roughly what we call daydreaming. But what daydreaming does, it breaks the
barriers of time and space and it juxtaposes scenarios that don’t occur in
reality.

And the same thing seems to happen in dreaming. So interestingly, all day
long our external circuits are turned on, those go for about 90 seconds.
And then we daydream, we integrate what we’ve just heard in the last 90
seconds in the external world with what our current concerns are and what
our future looks like. So I’m all for encouraging people to daydream and to
dream and to take lessons from that.

ALISON BEARD: For a lot of jobs, creativity sometimes feels like something
that you have to do on top of your daily rote work, and it might not even
be welcomed. So what advice do you have for people in that situation?

GABRIELLA ROSEN KELLERMAN: Part of the work of improving our creative
abilities is understanding what do we mean by creativity, and debunking the
myth of, again, this lone creative genius with the distal vision. We’re all
doing creative things every day, and so understanding what those are and
what those look like is part of the first step in building creative
self-efficacy.

So for someone who’s feeling burdened by creativity or maybe daunted in the
way that you’re describing, Alison, they probably have a low self-belief in
their own creative abilities. Creativity, for those who have a higher
self-belief, is something that we feel it’s easy for us to access. We’re
confident that we can come up with some ideas. Creative self-efficacy is
built very effectively through support and observation from influential
others.

ALISON BEARD: What can managers do to cultivate different types of
creativity on their teams?

GABRIELLA ROSEN KELLERMAN: Managers have a really critical role to play
here in building the creative self-efficacy of the individuals on their
teams, first and foremost. Managers have a huge influence on whether the
people on their teams see themselves as creative and successfully so. It’s
important to notice the little things, so little innovations in process, in
structure, in response to a customer complaint. Notice them, recognize
them, call them out. As you build the creative self-efficacy of the
individuals on your team, you increase the quality of the creative output
that you’ll see from those individuals.

It’s also important for managers to hold the bar of what is the realm of
the possible. So the group that we form in a team will quickly create norms
around how big do we want to think about this problem? And if we don’t
think big enough about the problem to begin with, then we’re sort of
already sunk before we’ve left the gate. So how do you position teams with
individuals within them in particular who can broaden that realm, who can
lift the ceiling on what people think is acceptable to be introducing into
the conversation? So that before we start narrowing and picking a solution,
we have the broadest set of ideas on the table to begin with.

ALISON BEARD: What about at the organization level? How can corporate
leaders foster a more creative culture that emphasizes and enhances these
different types of creativity?

GABRIELLA ROSEN KELLERMAN: Two things. The first is treating everyone as
creative. A lot of leadership competency structures today include
creativity as part of what they expect out of everyone in the organization.
Democratizing that idea, setting that broad expectation, it already goes a
huge way toward establishing this idea that everyone has that capability.
Everyone can and should and is expected to nurture it within the
organization.

The second is all about psychological safety and risk-taking. So cultures
that are great at creativity and innovation are able to celebrate
risk-taking even when the risk “fails,” even when the innovation is not a
success. If it was arrived in the right ways, with great solid thinking and
processes, celebrate it. Let everyone know that there’s good that comes
from all kinds of innovation and that the outcome isn’t necessarily going
to determine how your efforts were judged. Risk-taking is one of the
capabilities that’s important in general for success in this world of work.
And leaders set a really strong tone around that just by how they respond
when people at lower levels of the organization put themselves out there.

ALISON BEARD: Before we go, I want to talk about some of the other
essential human skills that you talk about in your book which seem to
complement creativity. Marty, you mentioned one of them before, which is
perspection. So tell me about that, the research you’ve done on it and how
you see it show up in the workplace.

MARTIN SELIGMAN: Well, I think it’s very important to be effectively
future-minded. Future-mindedness consists of the range of scenarios that
you can generate and your ability to choose among them. So for example, in
our work in the United States Army, we were interested in the fact that
people gravitate to the most catastrophic interpretation when things go
wrong. And so we have an exercise called putting it in perspective in which
we ask people first when something goes wrong.

And I’ll give you a military example. You’ve been out on a night march and
one member of your troop at midnight hasn’t shown up. Your catastrophic
thought is, he’s dead and I am really in trouble. So we have people first
to lay out the most catastrophic thinking. Then we have people lay out the
best possible consequence. Maybe the batteries are dead in his radio and
he’ll be here in five minutes. And then we have people, having contrasted
the best to the worst, to talk about the most realistic and to plan for it.
The most realistic here is something has gone wrong, he may be injured, and
what we need to do is retrace our steps and find him. Putting things in
perspective is a great tool for effective future-mindedness.

ALISON BEARD: And what about connection? That’s another chapter in the book
that you talk about, and surely that is important to work and creativity,
particularly when you’re trying to surround yourself with people who have
different types of creative modes than you.

GABRIELLA ROSEN KELLERMAN: Yeah. So every model of wellbeing includes
relationships and connection as a pillar of our psychological wellbeing. In
the modern workplace, there’s so many barriers to connection because we’re
separated in space, because we’re really strangers and we’re in these teams
that are constituting and reconstituting over and over again. And yet we
still need each other as much as ever for our wellbeing, and for our
creative work to be successful, it relies on collaboration.

And now more than ever, companies are focused not on customer satisfaction,
not even on customer experience, but customer delight. The bar just keeps
getting higher for this level of connection that we’re expected to achieve
with our customers, which again comes back to connection. And so for our
purposes, the task is how do we overcome these barriers in order to build
authentic deep connection and trust and to do so quickly? Because of
course, the pace of work today is so fast and we feel this sense of time
famine. There’s not enough time in the day. We call this rapid rapport and
we introduce a number of techniques for quick trust building across
difference.

ALISON BEARD: Thank you both for being here today. I really appreciate it.

GABRIELLA ROSEN KELLERMAN: Thanks so much, Alison.

MARTIN SELIGMAN: Thanks so much.

ALISON BEARD: That’s Gabriella Rosen Kellerman, a physician and executive
at BetterUp, and Martin Seligman, psychologist and professor at the
University of Pennsylvania. They’re coauthors of the new book Tomorrowmind
and the HBR article, “Cultivating the Four Kinds of Creativity.”

We have more episodes and more podcasts to help you manage your team, your
organization, and your career. Find them at hbr.org/podcasts or search HBR
in Apple Podcasts, Spotify, or wherever you listen.

This episode was produced by Mary Dooe. We get technical help from Rob
Eckhardt. Our audio product manager is Ian Fox. And Hannah Bates is our
audio production assistant. Thanks for listening to the HBR IdeaCast. We’ll
be back with a new episode on Tuesday. I’m Alison Beard.


发自我的 iPhone


Alex ***@***.***> 于 2023年5月24日周三 20:21写道：

**Comment by ac1982** [comment]
我试了下，偶尔复现。有两个办法可以解决，你用gpt-4模型，这样不会丢失sysytem。还有就是改变threshold的大小，调大100或者调小100。

**Comment by wuzimi** [comment]
Gpt4 的api还没有，想试试你说的第二个方法。另外有没有双语对照的计划？还有一点，我在对照使用中发现的。我还在用一个电子书翻译插件，好像书伴,
也是使用了OpenAI,但是我发现他那个翻译质量更加好，不知道什么原因导致。你的好像用的对话模型吧，是不是和这个有关？

Alex ***@***.***> 于 2023年5月28日周日 13:43写道：

**Comment by ac1982** [comment]
GPT4的翻译质量就更好啊。

**Comment by wuzimi** [comment]
你理解错意思了。GPT4是更好。我说的同样是GPT3.5, 你的这个翻译结果与那个电子书的翻译插件相比，感觉要差些，有时间你可以测一下。

Alex ***@***.***> 于2023年5月28日周日 20:42写道：

**Comment by ac1982** [comment]
OK,谢谢反馈
