### ISSUE TITLE
结束后找不到翻译的书籍

### ISSUE THREAD

**Issue by zhang19980518** [ac1982/eBook-translator#3]
遍历Level:2结束，缓冲区仍有Buffer
Buffer Tokens：126 
翻译Buffer:
<p class="level2ix"><a id="pgfId-676102"></a><a class="index" href="../Text/07.htm#marker-1039591">defining Service manifest with 234</a></p><p class="grouptitlesix"><a id="pgfId-676104"></a>Z<a id="Z"></a></p><p class="level1ix"><a id="pgfId-676106"></a><a class="index" href="../Text/02.htm#marker-1012900">zero-trust 41</a></p>

这段文本翻译后的内容:
<p class="level2ix"><a id="pgfId-676102"></a><a class="index" href="../Text/07.htm#marker-1039591">使用 234 定义服务清单</a></p><p class="grouptitlesix"><a id="pgfId-676104"></a>Z<a id="Z"></a></p><p class="level1ix"><a id="pgfId-676106"></a><a class="index" href="../Text/02.htm#marker-1012900">零信任 41</a></p>
程序到这就停了  然后自己退出了  也没有生成文件

**Comment by ac1982** [comment]
失败的文件不会生成翻译后的epub的。你上传的文件都无法打开啊，可以贴文本，谢谢。
